baseURL = "http://example.org/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = ["LoveIt"]

# 网站标题
title = "Chan-技术与生活"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true
# 是否使用 lightgallery
lightgallery = true

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-search-fuse-js"

# 作者配置
[author]
    name = "Chan"
    email = "czq181020@gmail.com"
    link = ""

# 菜单配置
[menu]
    # 一级菜单
    [[menu.main]]
        weight = 1
        identifier = "posts"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fas fa-fw fa-archive'></i>"
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        name = "归档"
        url = "/posts/"
        title = ""
    [[menu.main]]
        weight = 2
        identifier = ""
        pre = "<i class='fas fa-fw fa-at'></i>"
        post = ""
        name = "关于"
        url = "/about/关于/"
        title = ""
    [[menu.main]]
        weight = 3
        pre = "<i class='fas fa-fw fa-fan fa-spin'></i>"
        name = "友链"
        identifier = "friends"
        url = "/friends/"
    [[menu.main]]
        weight = 4
        pre = "<i class='fas fa-fw fa-search'></i>"
        name = "搜索"
        identifier = "search"
        url = "/search/"
#    [[menu.main]]
#        weight = 5
#        pre = "<i class='fas fa-fw fa-search'></i>"
#        name = "相册"
#        identifier = ""
#        url = "/about/photo/"

    # 二级菜单
    [[menu.main]]
        weight = 1
        parent = "posts"
        pre = "<i class='fas fa-fw fa-th'></i>"
        name = "分类"
        identifier = "categories"
        url = "/categories/"
    [[menu.main]]
        weight = 2
        parent = "posts"
        identifier = "tags"
        pre = "<i class='fas fa-fw fa-tag'></i>"
        # 跳转新标签页打开
        # post = "_blank"
        name = "标签"
        url = "/tags/"
        title = ""

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false
    [markup.goldmark.renderer]
        # 解除禁用HTML代码
        unsafe = true
[params]
    [params.app]
        [params.search]
            enable = false
