baseURL = "https://www.chenzqi.cn/"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = ["LoveIt"]

# 网站标题
title = "辰深-技术与生活"

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true
# 是否使用 lightgallery
#lightgallery = true
# 启用表情符号
enableEmoji = true

[module]
  [[module.imports]]
    path = "github.com/kaushalmodi/hugo-search-fuse-js"

# 作者配置
[author]
    name = "辰深"
    email = "czq181020@gmail.com"
    link = ""

# 菜单配置
[menu]
    # 一级菜单
    [[menu.main]]
        weight = 1
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = "<i class='fas fa-fw fa-archive'></i>"
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
        identifier = "posts"
        url = "/posts/"
        name = "归档"
        title = "归档"
    [[menu.main]]
        weight = 3
        pre = "<i class='fas fa-fw fa-fan fa-spin'></i>"
        identifier = ""
        url = "/about/friends/"
        name = "友链"
        title = "友链"
    [[menu.main]]
        weight = 4
        pre = "<i class='fas fa-fw fa-search'></i>"
        identifier = "search"
        url = "/search/"
        name = "搜索"
        title = "搜索"
    [[menu.main]]
        weight = 5
        pre = "<i class='fas fa-fw fa-at'></i>"
        identifier = ""
        url = "/about/photo/"
        name = "相册"
        title = "相册"
    [[menu.main]]
        weight = 7
        pre = "<i class='fas fa-address-card fa-fw'></i>"
        identifier = ""
        url = "/about-me/"
        name = "关于"
        title = "关于"

    # 二级菜单
    [[menu.main]]
        weight = 1
        parent = "posts"
        pre = "<i class='fas fa-fw fa-th'></i>"
        identifier = "categories"
        url = "/categories/"
        name = "分类"
        title = "分类"
    [[menu.main]]
        weight = 2
        parent = "posts"
        identifier = "tags"
        pre = "<i class='fas fa-fw fa-tag'></i>"
        # 跳转新标签页打开
        # post = "_blank"
        url = "/tags/"
        name = "标签"
        title = "标签"

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
    [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
        noClasses = false
    [markup.goldmark.renderer]
        # 解除禁用HTML代码
        unsafe = true

[params]
    [params.app]
        [params.search]
            enable = false

    # Header config
    # 页面头部导航栏配置
    [params.header.title]
        name = "辰深·"
        # you can add extra information before the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = ""
        # you can add extra information after the name (HTML format is supported), such as icons
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = '<i class="fa-solid fa-c"></i><i class="fa-solid fa-s" style="color: #B197FC;"></i>'


# Footer config
    # 页面底部信息配置
    [params.footer]
        enable = true
        # Custom content (HTML format is supported)
        # 自定义内容 (支持 HTML 格式)
        custom = "<a target='_blank'><img style='width: 70px; height: 20px;' src='https://gohugo.io/images/hugo-logo-wide.svg'></a>"
        # whether to show Hugo and theme info
        # 是否显示 Hugo 和主题信息
        hugo = false
        # whether to show copyright info
        # 是否显示版权信息
        copyright = true
        # whether to show the author
        # 是否显示作者
        author = true
        # site creation time
        # 网站创立年份
        since = 2018
        # ICP info only in China (HTML format is supported)
        # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
        icp = "<a target='_blank' href='https://beian.mps.gov.cn/' style='font-weight:500'>豫ICP备2021019462</a>"
        # license info (HTML format is supported)
        # 许可协议信息 (支持 HTML 格式)
        license= "<a rel='license external nofollow noopener noreffer' href='https://creativecommons.org/licenses/by-nc/4.0/' target='_blank'>CC BY-NC 4.0</a>"

    # Home page config
    # 主页信息设置
    [params.home]
        # amount of RSS pages
        # RSS 文章数目
        rss = 10
        # Home page profile
        # 主页个人信息
        [params.home.profile]
            enable = true
            # Gravatar Email for preferred avatar in home page
            # Gravatar 邮箱，用于优先在主页显示的头像
            gravatarEmail = ""
            # URL of avatar shown in home page
            # 主页显示头像的 URL
            avatarURL = "https://qn.chenzqi.cn/chenshen/logo.png"
            # title shown in home page (HTML format is supported)
            # 主页显示的网站标题 (支持 HTML 格式)
            title = ""
            # subtitle shown in home page (HTML format is supported)
            # 主页显示的网站副标题 (允许 HTML 格式)
            subtitle = "⛵停在港口的船是安全的，但这不是造船的目的."
            # whether to use typeit animation for subtitle
            # 是否为副标题显示打字机动画
            typeit = true
            # whether to show social links
            # 是否显示社交账号
            social = true
            # disclaimer (HTML format is supported)
            # 免责声明 (支持 HTML 格式)
            disclaimer = ""
            # Home page posts
            # 主页文章列表
            [params.home.posts]
                enable = true
                # special amount of posts in each home posts page
                # 主页每页显示文章数量
                paginate = 6